"""86eab194ec1f_create_tennis_data_table
Revision ID: 86eab194ec1f
Revises:
Create Date: 2020-03-08 13:42:26.041388
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
import logging
from db.models import Tennis
import pandas as pd

# revision identifiers, used by Alembic.
revision = '86eab194ec1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    # data_upgrades()


def downgrade():
    # data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tennis_data',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('atp', sa.Integer(), nullable=True),
                    sa.Column('location', sa.String(), nullable=True),
                    sa.Column('tournament', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    data_upgrades()
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tennis_data')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    session = Session(bind=op.get_bind())
    tennis_data = pd.read_excel(r'data/2011.xls')

    for _, row in tennis_data.iterrows():
        session.add(
            Tennis(
                atp=row['ATP'],
                location=row['Location'],
                tournament=row['Tournament'],
            )
        )
    session.commit()


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
